spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  liquibase:
    enabled: false

kakao:
  daum:
    search-url: http://test-url
  api-key: test
  oauth2-token-url: https://test-oauth2.kakao.com
  api-url: https://test-api.kakao.com
google:
  oauth2-token-url: https://test.googleapis.com
  api-url: https://test.google-api.com

jwt:
  secret: 1231231321321secret1231231321321secret1231231321321secret1231231321321secret1231231321321secret
  access-expiration: 3600000
  refresh-expiration: 604800000

oauth2:
  kakao:
    client-id: test-client-id
    client-secret: test-client-secret
    redirect-uri: test-redirect-uri
    scope:
      - "profile_nickname"
  google:
    client-id: test-client-id
    client-secret: test-client-id
    redirect-uri: test-client-secret
    scope:
      - "email"
      - "profile"
