spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


logging:
  level:
    org.debooklog.debooklogserver.book.infra.api.KakaoDaumSearchApi: DEBUG

spring.cloud.openfeign:
  client:
    config:
      kakao-daum-search-api:
        loggerLevel: full

kakao:
  daum:
    search-url: https://dapi.kakao.com