spring.application.name: debooklog-server
spring.profiles.active: local
spring:
  config:
    import:
      - application-secret.yml
---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.debooklog.debooklogserver.book.infrastructure.api.org.debooklog.debooklogserver.book.infrastructure.client.api.KakaoDaumSearchApi: DEBUG

spring.cloud.openfeign:
  client:
    config:
      kakao-daum-search-api:
        loggerLevel: full

kakao:
  daum:
    search-url: https://dapi.kakao.com

jwt:
  secret: 1231231321321secret1231231321321secret1231231321321secret1231231321321secret1231231321321secret
  access-expiration: 3600000
  refresh-expiration: 604800000
---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

kakao:
  daum:
    search-url: http://test-url
  api-key: test

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  access-expiration: 3600000
  refresh-expiration: 604800000
