spring.application.name: debooklog
spring:
  profiles:
    active: local
  config:
    import:
      - application-secret.yml
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${${spring.datasource.driver-class-name}
kakao:
  daum:
    search-url: ${kakao.daum.search-url}
  oauth2-token-url: ${kakao.oauth2-token-url}
  api-url: ${kakao.api-url}
google:
  oauth2-token-url: ${google.oauth2-token-url}
  api-url: ${google.api-url}

jwt:
  secret: ${jwt.secret}
  access-expiration: ${jwt.access-expiration}
  refresh-expiration: ${jwt.refresh-expiration}
