spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debooklog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

spring.cloud.openfeign:
  client:
    config:
      kakao-daum-search-api:
        loggerLevel: full

logging:
  level:
    org.debooklog.adapter.client.book.api.KakaoDaumSearchApi: DEBUG

jwt:
  secret: 1231231321321secret1231231321321secret1231231321321secret1231231321321secret1231231321321secret
  access-expiration: 3600000
  refresh-expiration: 604800000

kakao:
  daum:
    search-url: https://dapi.kakao.com
  oauth2-token-url: https://kauth.kakao.com
  api-url: https://kapi.kakao.com

google:
  oauth2-token-url: https://oauth2.googleapis.com
  api-url: https://www.googleapis.com

