spring.application.name: debooklog-server
spring.profiles.active: local
spring:
  config:
    import:
      - application-secret.yml
---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.debooklog.debooklogserver.book.infrastructure.api.org.debooklog.debooklogserver.book.infrastructure.client.api.KakaoDaumSearchApi: DEBUG

spring.cloud.openfeign:
  client:
    config:
      kakao-daum-search-api:
        loggerLevel: full

kakao:
  daum:
    search-url: https://dapi.kakao.com
  oauth2-token-url: https://kauth.kakao.com

jwt:
  secret: 1231231321321secret1231231321321secret1231231321321secret1231231321321secret1231231321321secret
  access-expiration: 3600000
  refresh-expiration: 604800000

---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

kakao:
  daum:
    search-url: http://test-url
  api-key: test
  oauth2-token-url: https://test.kakao.com

jwt:
  secret: 1231231321321secret1231231321321secret1231231321321secret1231231321321secret1231231321321secret
  access-expiration: 3600000
  refresh-expiration: 604800000

oauth2:
  kakao:
    client-id: test-client-id
    client-secret: test-client-secret
    redirect-uri: test-redirect-uri
    scope:
      - "profile_nickname"
  google:
    client-id: test-client-id
    client-secret: test-client-id
    redirect-uri: test-client-secret
    scope:
      - "email"
      - "profile"
